### ISSUE TITLE
Installation failure in either pip install or conda install

### ISSUE THREAD

**Issue by younglululu** [openAGI/datum#8]
**Short description**
Description of the bug.

**Environment information**
* Operating System: ubuntu 18.04
* All python/tensorflow version follow environment.yml 

** Error info using conda install

conda env create -f environment.yml
Collecting package metadata: done
Solving environment: done
==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.10.3
Please update conda by running
    $ conda update -n base conda
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
[u'/home/yanglu/anaconda3/envs/datum/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/yanglu/Documents/datum/tmpXTxcEC.requirements.txt']
Pip subprocess output:
Collecting tensorflow==2.5.0 (from -r file:requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/aa/fd/993aa1333eb54d9f000863fe8ec61e41d12eb833dea51484c76c038718b5/tensorflow-2.5.0-cp37-cp37m-manylinux2010_x86_64.whl
Collecting opencv-python==4.5.2.52 (from -r file:requirements.txt (line 3))
Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement opencv-python==4.5.2.52 (from -r file:requirements.txt (line 3)) (from versions: 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 4.0.0.21, 4.0.1.23, 4.0.1.24, 4.1.0.25, 4.1.1.26, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56)
ERROR: No matching distribution found for opencv-python==4.5.2.52 (from -r file:requirements.txt (line 3))
WARNING: You are using pip version 19.1.1, however version 21.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
CondaEnvException: Pip failed

** Error info using pip install

Collecting datum
  Using cached datum-1.2.0.tar.gz (40 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/yanglu/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pFVc1m/datum/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pFVc1m/datum/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-SEXAtA
         cwd: /tmp/pip-install-pFVc1m/datum/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pFVc1m/datum/setup.py", line 9, in <module>
        from setuptools import find_namespace_packages, setup
    ImportError: cannot import name find_namespace_packages
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by n3011** [comment]
Which python version are you using? 
This package works with python >= 3.7

You can install by running `pip install datum`

**Comment by younglululu** [comment]
Yes, I am using python 3.7 by creating a new conda environ suggested by environment.yml.

And pip install failed as well. :(

**Comment by n3011** [comment]
You don't need to build an environment using the `environment.yml` file when you install datum using `pip`.

If you are getting errors, that means that your development environment is not set up correctly.

**Comment by younglululu** [comment]
even if my development environment is not set up correctly, building a new development environment by following the suggested environment.yml, as a tedious solution, should always work, right? If it's not, maybe there is something wrong. @jmschrei

**Comment by jmschrei** [comment]
My understanding is that using conda to set up the environment, as you did, should always create a working environment even if your base one is incompatible with the prereqs. That's the primary motivation behind having virtual environments at all, right? What happens when you create a new blank environment Py3.7 environment and try pip installing into that?

**Comment by pmeier** [comment]
@younglululu Are you on macOS? If so, which version? 

By looking at the files associated with the PyPI releases, the following architectures are supported by the three most recent releases of `opencv-python`:

- [`4.5.1.48`](https://pypi.org/project/opencv-python/4.5.1.48/#files): `macosx_10_13_x86_64`
- [`4.5.2.52`](https://pypi.org/project/opencv-python/4.5.2.52/#files): `macosx_10_15_x86_64`
- [`4.5.3.56`](https://pypi.org/project/opencv-python/4.5.3.56/#files): `macosx_10_15_x86_64`, `macosx_11_0_arm64` (only Python 3.7 and higher)

@n3011 If there is no specific reason for the `opencv==4.5.2.52` pin, I suggest you remove or relax it.

**Comment by pmeier** [comment]
@younglululu Are you an ARM machine?

By looking at the files associated with the PyPI releases, `opencv-python==4.5.2.52` was not released for ARM:

- [`4.5.1.48`](https://pypi.org/project/opencv-python/4.5.1.48/#files): `manylinux2014_aarch64`, `manylinux2014_i686`, `manylinux2014_x86_64`
- [`4.5.2.52`](https://pypi.org/project/opencv-python/4.5.2.52/#files): `manylinux2014_x86_64`
- [`4.5.3.56`](https://pypi.org/project/opencv-python/4.5.3.56/#files): `manylinux2014_aarch64`, `manylinux2014_x86_64`

@n3011 If there is no specific reason for the pin, I suggest you remove or relax it.

**Comment by n3011** [comment]
@pmeier I will relax the requirements to `4.5.*`

**Comment by younglululu** [comment]
My environment is Ubuntu 18.04, not mac. 
I don't think I have an ARM machine, it should be conventional windows-intel architecture.
